# Generated by Django 4.2.4 on 2023-10-23 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("schedule", "Schedule"),
                            ("reschedule", "Reschedule"),
                            ("promotional", "Promotional"),
                            ("system", "System"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "push_notification",
            },
        ),
        migrations.CreateModel(
            name="UserPushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.pushnotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_push_notification",
            },
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="users",
            field=models.ManyToManyField(
                through="administrator.UserPushNotification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
