# Generated by Django 4.2.4 on 2023-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0002_userpaymentprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpaymentprice",
            name="price",
            field=models.FloatField(),
        ),
    ]
