# Generated by Django 4.2.4 on 2023-11-02 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="initial_schedule_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointments",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
