# Generated by Django 4.2.4 on 2023-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="medical_license",
            field=models.FileField(
                blank=True, null=True, upload_to="doctor/medical_license"
            ),
        ),
    ]
