# Generated by Django 4.2.4 on 2023-10-26 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "doctor",
            "0003_remove_consultation_consult_consultation_appointment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="patient",
        ),
    ]
