# Generated by Django 4.2.4 on 2023-10-20 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_timeslot_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointments",
            name="time",
        ),
        migrations.AddField(
            model_name="appointments",
            name="schedule_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 20, 7, 51, 12, 468967, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rescheduled", "Rescheduled"),
                    ("free consult", "Free Consult"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("leave_date", models.DateField()),
                ("is_sanction", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctors"
                    ),
                ),
            ],
            options={
                "db_table": "doctor_leave",
            },
        ),
    ]
