# Generated by Django 4.2.4 on 2023-11-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "doctor",
            "0003_rename_no_cost_consult_appointments_free_meetings_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
