# Generated by Django 4.2.4 on 2023-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_appointments_meeting_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="is_attend_by_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="is_attend_by_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("scheduled", "scheduled"),
                    ("rescheduled", "rescheduled"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("free_scheduled", "free_scheduled"),
                    ("unanswered_patient", "unanswered_patient"),
                    ("unanswered_doctor", "unanswered_doctor"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
