# Generated by Django 4.2.4 on 2023-10-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0004_remove_consultation_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="paid_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="pay_mode",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="pre_health_issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patients",
            name="treatment_allergies",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patients",
            name="treatment_undergoing",
            field=models.BooleanField(default=False),
        ),
    ]
