# Generated by Django 4.2.4 on 2023-10-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_alter_patients_email_alter_patients_paid_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patients",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="pay_mode",
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("paid_amount", models.FloatField()),
                ("pay_mode", models.CharField(max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctor.patients",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
