# Generated by Django 4.2.4 on 2023-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_appointments_is_attend_by_doctor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotePad",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="additional_note",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="pre_health_issue",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="pre_health_issue_text",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="treatment_allergies",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="treatment_allergies_text",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="treatment_undergoing",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="treatment_undergoing_text",
        ),
        migrations.AddField(
            model_name="appointments",
            name="additional_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointments",
            name="pre_health_issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="pre_health_issue_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointments",
            name="treatment_allergies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="treatment_allergies_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointments",
            name="treatment_undergoing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointments",
            name="treatment_undergoing_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="pass_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("scheduled", "scheduled"),
                    ("rescheduled", "rescheduled"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("expired", "expired"),
                    ("free_scheduled", "free_scheduled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("scheduled", "scheduled"),
                    ("rescheduled", "rescheduled"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("expired", "expired"),
                    ("free_scheduled", "free_scheduled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
