# Generated by Django 4.2.4 on 2023-10-20 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_alter_availability_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="is_available",
        ),
    ]
