# Generated by Django 4.2.4 on 2023-10-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "doctor",
            "0006_remove_patients_paid_amount_remove_patients_pay_mode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="doctor",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="doctor.doctors",
            ),
            preserve_default=False,
        ),
    ]
