# Generated by Django 4.2.4 on 2023-11-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0007_transactions_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointments",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="appointment",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="doctor.appointments",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactions",
            name="trans_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("scheduled", "scheduled"),
                    ("rescheduled", "rescheduled"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("free_scheduled", "free_scheduled"),
                    ("unanswered_patient", "unanswered_patient"),
                    ("unanswered_doctor", "unanswered_doctor"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
