# Generated by Django 4.2.4 on 2023-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0008_remove_transactions_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "paid"), ("unpaid", "unpaid")],
                default="unpaid",
                max_length=50,
            ),
        ),
    ]
